// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RouletteGame.Infrastructure.Persistence;

#nullable disable

namespace RouletteGame.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20240608150335_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("RouletteGame.Core.Domain.Entities.Player", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.HasKey("Name");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
